// Code Generated by github.com/stanistan/veun-http-demo/cmd/lit-gen; DO NOT EDIT.
package page

import (
	"context"
	_ "embed"

	"github.com/stanistan/veun"
)

//go:embed template.tpl
var tpl string
var template = veun.MustParseTemplate("page", tpl)

type Data struct {
	Title    string
	CSSFiles []string
	JSFiles  []string
}

type view struct {
	body veun.AsView
	data Data
}

func (v view) View(_ context.Context) (*veun.View, error) {
	return veun.V(veun.Template{
		Tpl:   template,
		Slots: veun.Slots{"body": v.body},
		Data:  v.data,
	}), nil
}

type DataMutator interface {
	SetPageData(d *Data)
}

func View(v veun.AsView, data Data) view {
	return view{
		body: v,
		data: mutateData(data, v),
	}
}

func mutateData(d Data, with any) Data {
	if m, ok := with.(DataMutator); ok {
		m.SetPageData(&d)
	}

	return d
}
