// CODE GENERATED BY lit-gen; DO NOT EDIT.
package md

import (
	"bytes"
	"context"
	"html/template"

	"github.com/stanistan/veun"
	"github.com/stanistan/veun/html"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

var markdown = goldmark.New(
	goldmark.WithExtensions(extension.GFM),
)

type Markdown struct {
	Bytes    []byte
	Markdown goldmark.Markdown
}

func (m Markdown) AsHTML(_ context.Context) (template.HTML, error) {
	var out bytes.Buffer
	if err := m.Markdown.Convert(m.Bytes, &out); err != nil {
		return template.HTML(""), err
	}

	return template.HTML(out.String()), nil
}

type view struct {
	Bytes []byte
}

func (v view) View(_ context.Context) (*veun.View, error) {
	return veun.V(Markdown{
		Bytes:    v.Bytes,
		Markdown: markdown,
	}), nil
}

func View(bs []byte) veun.AsView {
	return html.Article(nil, view{Bytes: bs})
}
