// CODE GENERATED BY lit-gen; DO NOT EDIT.
package main

import (
	"embed"
	"log/slog"
	"net/http"
	"os"
)

var (
	//go:embed static
	staticFiles embed.FS
)

func staticFileServer() http.Handler {
	return http.FileServer(http.FS(staticFiles))
}

func initLogger() {
	var logHandler slog.Handler
	if os.Getenv("ENV") == "dev" {
		logHandler = slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
			Level: slog.LevelDebug,
		})
	} else {
		logHandler = slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
			Level: slog.LevelInfo,
		})
	}

	slog.SetDefault(slog.New(logHandler))
}
