// CODE GENERATED BY lit-gen; DO NOT EDIT.
package main

import (
	"log/slog"
	"net/http"
	"os"
	"time"
)

func main() {

	initLogger()

	var addr string
	if port := os.Getenv("PORT"); port != "" {
		addr = ":" + port
	} else {
		addr = ":8080"
	}

	s := &http.Server{
		Addr:    addr,
		Handler: server(), // server! we'll fill this in the next one

		// logging
		ErrorLog: slog.NewLogLogger(
			slog.Default().Handler(), slog.LevelWarn,
		),

		// timeouts
		ReadTimeout:  1 * time.Second,
		WriteTimeout: 5 * time.Second,
		IdleTimeout:  5 * time.Second,
	}

	slog.Info("starting server", "addr", addr)
	if err := s.ListenAndServe(); err != nil {
		slog.Error("server stopped", slog.String("err", err.Error()))
	}

}
