// Code Generated by github.com/stanistan/veun-http-demo/cmd/lit-gen; DO NOT EDIT.
package main

import (
	"github.com/stanistan/veun/vhttp/request"

	"github.com/stanistan/veun-http-demo/internal/view/page"
)

const (
	cssPath     = "/static/styles.css"
	htmxPath    = "/static/htmx.1.9.9.min.js"
	prismJSPath = "/static/prism.js"
)

func htmlPage(r request.Handler) request.Handler {
	return page.Handler(r, page.Data{
		Title:    "veun-http (demo)",
		CSSFiles: []string{cssPath},
		JSFiles:  []string{htmxPath, prismJSPath},
	})
}
