// Code Generated by github.com/stanistan/veun-http-demo/cmd/lit-gen; DO NOT EDIT.
package main

import (
	"net/http"

	"github.com/stanistan/veun/vhttp"
	"github.com/stanistan/veun/vhttp/handler"

	"github.com/stanistan/veun-http-demo/internal/view/page"
)

var (
	h  = vhttp.Handler
	hf = vhttp.HandlerFunc
)

var html = page.Handler(page.Data{
	Title:    "veun-http (demo)",
	CSSFiles: []string{"/static/styles.css"},
	JSFiles:  []string{"/static/htmx.1.9.9.min.js", "/static/prism.js"},
})

func routes() http.Handler {
	mux := http.NewServeMux()

	mux.Handle("/docs", h(html(docsIndex)))

	mux.Handle("/docs/", http.StripPrefix("/docs/", h(html(docsPage))))

	mux.Handle("/", handler.OnlyRoot(h(html(index))))

	return handler.Checked(mux, staticFileServer())

}
